trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Installing dependencies..."
    sudo apt-get update
    sudo apt-get install -y unzip curl
  displayName: 'Install Dependencies'

# Step 2: Detect Chrome version and download ChromeDriver
- script: |
    echo "Detecting Chrome version..."
    sudo apt-get install -y google-chrome-stable
    CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
    echo "Detected Chrome major version: $CHROME_VERSION"

    echo "Fetching matching ChromeDriver version..."
    CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
    echo "Matched ChromeDriver version: $CHROMEDRIVER_VERSION"

    echo "Downloading ChromeDriver..."
    curl -O https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    chmod +x chromedriver
    sudo mv chromedriver /usr/local/bin/
  displayName: 'Download and Setup ChromeDriver'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
