# Azure DevOps Pipeline YAML File for Maven Build and ChromeDriver Setup
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Install dependencies
- script: |
    echo "Installing dependencies..."
    sudo apt-get update
    sudo apt-get install -y unzip curl
  displayName: 'Install Dependencies'

# Step 2: Download a fixed ChromeDriver version
- script: |
    echo "Downloading ChromeDriver version 114.0.5735.90..."
    curl -O https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
    unzip chromedriver_linux64.zip
    chmod +x chromedriver
    sudo mv chromedriver /usr/local/bin/
  displayName: 'Download and Setup ChromeDriver'

# Step 3: Run Maven Build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
  displayName: 'Run Maven Build'

# Step 4: Copy WAR Files
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'
  displayName: 'Copy WAR Files'

# Step 5: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'
